dist:
 - bionic
language:
 - java
jdk:
 - openjdk8
env:
 - SCRIPT_ARG=hello
script:
 - ./make
 - ./test "$SCRIPT_ARG" "$HOME" "$JRUBY_OPTS" "$TRAVIS_BUILD_WEB_URL" "$TRAVIS_EVENT_TYPE" "$test_var_travis_1" "$test_var_travis_2"
notifications:
 email:
  - hassaanirshad88@gmail.com
